### ISSUE TITLE
Broken on python3.8 and python3.9

### ISSUE THREAD

**Issue by rmcgibbo** [lihaoyi/macropy#103]
Is this package still maintained? It appears to be broken on python3.8 and python3.9 with errors like this.

```
Traceback (most recent call last):
  File "run_tests.py", line 5, in <module>
    import macropy.test
  File "/build/source/macropy/test/__init__.py", line 14, in <module>
    from . import case_classes
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/build/source/macropy/core/import_hooks.py", line 147, in find_spec
    code, tree = self.expand_macros(source, origin, spec)
  File "/build/source/macropy/core/import_hooks.py", line 113, in expand_macros
    return compile(tree, filename, "exec"), new_tree
TypeError: required field "posonlyargs" missing from arguments
```

FYI. A different report of the same bug, which has a possible fix, is here: https://github.com/xonsh/xonsh/issues/3271

**Comment by shaunc** [comment]
... sigh ... and it looks so cool, too.
