### ISSUE TITLE
Test breakage in core/test/exporters

### ISSUE THREAD

**Issue by macobo** [lihaoyi/macropy#57]
The tests under core/test/exporters/**init**.py fail for me under python2.7. 

```
======================================================================
ERROR: test_pyc_exporter (macropy.core.test.exporters.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macobo/projects/macropy/macropy/core/test/exporters/__init__.py", line 33, in test_pyc_exporter
    f = open(__file__ + "/../pyc_cache.py", "a")
IOError: [Errno 20] Not a directory: '/home/macobo/projects/macropy/macropy/core/test/exporters/__init__.pyc/../pyc_cache.py'

======================================================================
ERROR: test_save_exporter (macropy.core.test.exporters.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macobo/projects/macropy/macropy/core/test/exporters/__init__.py", line 53, in test_save_exporter
    macropy.exporter = SaveExporter(__file__ + "/../exported", __file__ + "/..")
  File "/home/macobo/projects/macropy/macropy/core/exporters.py", line 20, in __init__
    shutil.copytree(root, directory)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 20] Not a directory: '/home/macobo/projects/macropy/macropy/core/test/exporters/__init__.pyc/..'

----------------------------------------------------------------------
```

`test_save_exporter` can be fixed by properly using the os.path module get parent directory path. This is outlined in the following commit: https://github.com/macobo/macropy/commit/543bc6344405e3fb0732fe92798268833c2cf542
Even after that `test_pyc_exporter` fails for me with an AssertionError on the last line.

```
======================================================================
FAIL: test_pyc_exporter (macropy.core.test.exporters.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macobo/projects/macropy/macropy/core/test/exporters/__init__.py", line 52, in test_pyc_exporter
    assert (pyc_cache_count, pyc_cache_macro_count) == (8, 5), (pyc_cache_count, pyc_cache_macro_count)
AssertionError: (8, 4)

----------------------------------------------------------------------
```

**Comment by davidshepherd7** [comment]
I'm seeing this issue as well, could you merge the pull request?
