### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by AmjadHD** [lihaoyi/macropy#90]
```python
from macropy.tracing import macros, trace
trace[[len(x)*3 for x in ["omg", "wtf", "b" * 2 + "q", "lo" * 3 + "l"]]]
```
gives:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Tfach\testmacropy.py", line 2, in <module>
    trace[[len(x)*3 for x in ["omg", "wtf", "b" * 2 + "q", "lo" * 3 + "l"]]]
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\macropy\core\macros.py", line 32, in __getitem__
    raise TypeError(self.msg.replace("%s", self.func.__name__))
TypeError: Macro `trace` illegally invoked at runtime; did you import it properly using `from ... import macros, trace`?
```
```python
from macropy.tracing import macros, trace
with trace:
    sum = 0
    for i in range(0, 5):
        sum = sum + 5
```
gives:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Tfach\testmacropy.py", line 2, in <module>
    with trace:
AttributeError: __enter__
```
```python
from macropy.string_interp import macros, s
A = 10
B = 5
print(s["{A} + {B} = {A + B}"])
# 10 + 5 = 15
```
gives
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Tfach\testmacropy.py", line 4, in <module>
    print(s["{A} + {B} = {A + B}"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\macropy\core\macros.py", line 32, in __getitem__
    raise TypeError(self.msg.replace("%s", self.func.__name__))
TypeError: Macro `s` illegally invoked at runtime; did you import it properly using `from ... import macros, s`?
```
basically nothing works, am i missing something here ?

* macropy: v1.1.0b2
* python: 3.7
* OS: Windows

**Comment by azazel75** [comment]
hi @AmjadHD, 

if you follow the basic tutorial [here](https://macropy3.readthedocs.io/en/latest/first_macro.html) you will see that you have to import macropy.activate _before_ importing the module containing the code that uses any macro

**Comment by AmjadHD** [comment]
pardon, the tutorial is about writing my own macro, but i'm using the already defined ones.
added `import macropy.activate` on the top of the 3 snippets above but it doesn't work.

**Comment by kuroop** [comment]
Same issue, not able to get it working. I tried the following after installing macropy3 and after reading the sample about ```with trace``` from readme:

```
Python 3.7.0 (default, Nov  4 2018, 00:07:25) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import macropy.activate
>>> from macropy.tracing import trace
>>> trace
<macropy.core.macros.WrappedFunction object at 0x7f60db72e518>
>>> with trace:
...     print("hello")
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __enter__
```

Is it not supposed to be used directly in the interpreter?

**Comment by AmjadHD** [comment]
so far the only way i found to make it work is to import the macro and use it in one file (e.g target.py) and import that file in another (e.g run.py) with `import macropy.activate` on top
_target.py_
```python
from macropy.tracing import macros, trace

with trace:
    sum([i for i in range(5)])
```
_run.py_
```python
import macropy.activate
import target
```

**Comment by kuroop** [comment]
Thanks @AmjadHD That's what I wanted.

**Comment by azazel75** [comment]
Can this be closed now?

**Comment by AmjadHD** [comment]
I guess yes
